version: '3.1'
services:
  app1:
    build: ./app1
    # restart: always
    networks:
      - testdockernet
    ports:
      - "3001:3001"
    expose:
      - "3001"
    environment:
      - CONFIG_MONGODB_USERNAME=${CONFIG_MONGODB_USERNAME:-default-user}
      - CONFIG_MONGODB_PASSWORD
    # volumes:
    #   - "app1-data:/app1"
  app2:
    container_name: 'newname-app2'
    build: ./app2
    # restart: always
    environment:
      - CONFIG_MONGODB_USERNAME
      - CONFIG_MONGODB_PASSWORD
    networks:
      - testdockernet
    ports:
      - "3002:3002"
    depends_on:
      - app1
  mongodb:
    build: ./mongodb
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      - testdockernet
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - "test-mongodb-data:/data/db"
  node-app3:
    build: ./node-app3
    # restart: always
    networks:
      - testdockernet
    ports:
      - "3003:3003"
networks:
  testdockernet:
    driver: bridge
volumes:
  test-rabbitmq-data:
    driver: local
  test-mongodb-data:
    driver: local
  test-redis-data:
    driver: local
